### ISSUE TITLE
[suggestion] More large mushroom variations and their mushroom counterparts

### ISSUE THREAD

**Issue by xkforce** [OrderedChaos-Dev/ProjectVibrantJourneys#63]
Vanilla has two types of large mushroom which can spawn naturally and be made artificially by using bone meal on mushrooms, red and brown.  What I'm suggesting is that more mushrooms like this be added but in different colors, shapes and sizes.  eg. green, blue, orange, white etc.  Also I think that the existing mushrooms should spread like vanilla ones do.  Currently, they appear to be static/a finite resource.

**Comment by mc-jt9** [comment]
Although it's untested, they should spread like the vanilla ones. I had the large mushrooms planned for the last update, but scrapped it for later. It will be added soon.
