### ISSUE TITLE
Debris consumes right click

### ISSUE THREAD

**Issue by Laike-Endaril** [OrderedChaos-Dev/ProjectVibrantJourneys#70]
**Describe the bug**
PVJ debris, such as the little rocks / sticks you find laying around, consume the right click event, preventing items from working correctly (potions, food, bow, etc).

This includes but may not be limited to...
...rocks
...twigs
...flower patches (but not clover patches; they're fine)

**Comment by mc-jt9** [comment]
They'll be getting a behavior update

**Comment by OrderedChaos-Dev** [comment]
Well it's been a while but I stopped working on the mod after getting busy with life. Groundcover behavior has changed for 1.15
