### ISSUE TITLE
In game Config changes affect lines other than those edited

### ISSUE THREAD

**Issue by crazyirishwrencher** [OrderedChaos-Dev/ProjectVibrantJourneys#72]
Issue occurs when editing the World generation settings in game. I set stalagmites & stalactites to zero (to avoid overlap with quark) and it sets multiple other settings to zero as well. Always in consecutive pairs just like the stalactites/stalagmites. I can manually set these back to default using the buttons.

**Comment by mc-jt9** [comment]
Hmm that doesn't sound right

**Comment by OrderedChaos-Dev** [comment]
The 1.12 version is no longer being developed, and stalagmites/stalactites are being dropped in favor of Quark's.
