### ISSUE TITLE
[Feature Request] Undergroud Biome Constructs ground cover

### ISSUE THREAD

**Issue by IronPiston** [OrderedChaos-Dev/ProjectVibrantJourneys#73]
Would you be able to add groundcover rocks for stone/sand/gravel types added by [Underground Biome Constructs](https://minecraft.curseforge.com/projects/underground-biomes)? I imagine these could be dynamically generated based on the textures. 

It could also check what type of stone is directly below the rock, that way it would match.

**Comment by mc-jt9** [comment]
That is possible, but I don't have plans for a 1.12.2 update.
