### ISSUE TITLE
[Feature Request] Toggle for terrain generation in superflat worlds

### ISSUE THREAD

**Issue by xkforce** [OrderedChaos-Dev/ProjectVibrantJourneys#75]
Basically what I am suggesting is that there be a way to toggle terrain gen on and off for superflat worlds.

**Comment by mc-jt9** [comment]
Ah yeah sounds like a neat idea

**Comment by xkforce** [comment]
Thank you for all the work you do on mods like this btw

**Comment by mc-jt9** [comment]
You're welcome! Glad you like it

**Comment by OrderedChaos-Dev** [comment]
Well looks like this isn't possible because Minecraft won't tell you want world type you're in
