### ISSUE TITLE
Bone meal 

### ISSUE THREAD

**Issue by SpGilbert** [OrderedChaos-Dev/ProjectVibrantJourneys#81]
Can you make it so bone meal on dirt spawns all the grass variants?
Can you also make it so when you use it on sand you can get sea oats and beach grass depending on the biome?

**Comment by mc-jt9** [comment]
Makes sense to me.

**Comment by OrderedChaos-Dev** [comment]
Added in recent update except grass variants, would involve modifying vanilla behavior
