### ISSUE TITLE
Crash with Aether legacy

### ISSUE THREAD

**Issue by Omni35** [OrderedChaos-Dev/ProjectVibrantJourneys#82]
**Describe the bug**
So, for some reason setting the 'Animal Density' to 0 in the config makes you crash after you spawn in the aether dimension. 

**Crash Log**
Crash report: https://pastebin.com/A2ire45J
Latest log: https://pastebin.com/7fUttLFH

**Comment by OrderedChaos-Dev** [comment]
Oops, I don't think I ever saw this issue. The 1.12 version isn't being developed anymore in favor of the 1.15 version.
