### ISSUE TITLE
Dynamic trees compat

### ISSUE THREAD

**Issue by SpGilbert** [OrderedChaos-Dev/ProjectVibrantJourneys#83]
Perhaps you should consider possibly eventually adding compatibility with dynamic trees. You are free to close this feature request if you don't want to add this feature. won't be offended if you do close it.

**Comment by DMNerd** [comment]
+ 1

**Comment by ThatLordGuy** [comment]
I see you already have integration for biomes o plenty and traverse. They both have dynamic trees compat mods already if you could just recognize when they are present and use their trees instead. So far as I've seen the only tree that doesn't have a dynamic model from BoP is the Mangrove.

**Comment by OrderedChaos-Dev** [comment]
Maybe one day...but unlikely
