### ISSUE TITLE
Fully disabling entities

### ISSUE THREAD

**Issue by SextupleTap** [OrderedChaos-Dev/ProjectVibrantJourneys#86]
In the configs there doesn't seem to be any way to hard disable entities, it seems like items associated with these entities (spawn eggs and summon-able by command) (or for mob specific drops such as with the shade) stick around too, so hard disabling all items/blocks, not just a select few would be nice as well along with hard disabling entities as well (instead of just setting their spawn weight to 0), currently you have the shade and the skeletal knight with spawn weights in the spawner pool for dungeons as well, I'd be nice if this was also configurable in the configs (whether it's just an enable or disable, or being able to change the spawner weights themselves).

**Comment by OrderedChaos-Dev** [comment]
The 1.12 version has stopped development, but I'm working on having a better config for 1.15.
