### ISSUE TITLE
[1.12.2] Goon crash with Performant's AI changes

### ISSUE THREAD

**Issue by katubug** [OrderedChaos-Dev/ProjectVibrantJourneys#92]
I accidentally hit enter too soon. I got this crash: https://pastebin.com/1BgSxQka

It mentions the Goon, and the Performant mod. I'm not sure who to report this to. Also, worth mentioning, I have a bunch of mods that affect AI, so it's possible this is a multi-mod conflict.

Thanks for your time!

**Comment by OrderedChaos-Dev** [comment]
Hi, the 1.12 version is no longer being developed. I am working on porting the mod to 1.15.
